### ISSUE TITLE
CSS improvement for Moodle4 and .1container

### ISSUE THREAD

**Issue by luiggisanso** [oliviervalentin/moodle-mod_stickynotes#18]
Hi @oliviervalentin 

I've tested your amazing plugin on a Moodle 4 (Moodle 4.0.1 (Build: 20220509)) and I have some bugs with a CSS element :
.1container

With boost, in the profile page (and account creation page), I have some custom profile fields with a rotation effect :-)
![AcY9GNqs](https://user-images.githubusercontent.com/1565841/179463819-913b2737-763a-4139-ac8e-aaf32862b713.png)

I need to add this css rule to neutralize the effect (no space between # and page):
```
#page-login-signup div[id*="1container"] {
    transform: rotate(0deg);
}
```
```
#page-user-editadvanced div[id*="1container"] {
    transform: rotate(0deg);
}
```

And I confirm it works on a Moodle 4 

Could you rename your .1container by .stickycontainer and update you css rules for example ?

Cheers.

**Comment by oliviervalentin** [comment]
Hi @luiggisanso,
indeed, there's a problem concerning style... The id "Xcontainer" is overriding another style from the core. I changed this name so it doesn't interract anymore in branch "updates". Can you confirm the problem disappeared before I merge it to main ?
Olivier

**Comment by luiggisanso** [comment]
Hi

Thanks for this quick improvement 👍 

It's ok now

Cheers.

**Comment by oliviervalentin** [comment]
OK I push it into main and close this issue.
Olivier
