### ISSUE TITLE
students can move sticky notes

### ISSUE THREAD

**Issue by ilanaBer** [oliviervalentin/moodle-mod_stickynotes#20]
Hi oliver,
 
There is an issue that a student can move other students sticky notes and also can move teacher sticky notes.
The move icon is not appear but the student can move the stickty note anyway.
Is it possible to change this in the permissions or to fix it in another way?

Thank you.

**Comment by luiggisanso** [comment]
Hi @oliviervalentin 

Yes, I confirm @ilanaBer observation, a student can move a teacher stickynote, even without move icon.
I think it's the classical behaviour to let all stickynotes to be moved around, it's a collaborative activity.

But it could be nice to have a setting to enable or disable this behaviour.

Not a bug, but an improvement or new feature ;-)
