### ISSUE TITLE
Column titel

### ISSUE THREAD

**Issue by cputzenlechner** [oliviervalentin/moodle-mod_stickynotes#23]
Hello Olivier,
we would like to create sticky notes in Moodle template courses that have 4 columns of headings (for feedback).
Unfortunately, when importing the Moodle template course, the column headings are not included.
Is there a way to keep the column headings for an import?

Kind regards
Christian

**Comment by oliviervalentin** [comment]
HI,
sounds like a problem in backup/restore coding... I will soon check this.
Just to be sure : when you import your backup, your four columns are here, but the title is empty (or get the default title "Column X"), is that right ?
Olivier

**Comment by cputzenlechner** [comment]
Hi Olivier,
yes, that is correct. The sticky note activity is available after import but without the column headings created in the template course. We would like to use the sticky notes as a visually attractive feedback tool (which we currently do in only a few Moodle courses). To manually create the column headings in several hundred Moodle courses is quite time-consuming. That's why we would like to include them in template courses.
(Please have a look at the 
![sticky-notes](https://github.com/oliviervalentin/moodle-mod_stickynotes/assets/147624573/19a6c1f6-ca26-4636-815c-135b400ae2ff)
Many thanks and best regards
Christian

**Comment by oliviervalentin** [comment]
OK understand... Seems to be a real bug in backup/restore function. Not the easiest part of Moodle for sure ! :'(
I'll try to fix it, stay tuned.

PS : ich sehe "Das hat Spass gemacht" : wenn ich ein Kind wäre, gehte ich am "Laguna", in Weil Am Rhein. Ich erinnere mich, dass der Slogan "NBass macht Spass" wäre ! Ha, meine elsässische Jugend :D 

Olivier

**Comment by oliviervalentin** [comment]
Hi Christian,
I started working on this problem. I'm a bit disappointed : when I save and restore the whole course (or just the activity) using the .mbz archive, all works fine.
But when I use the "Duplicate" option on the course with edit mode on, activity is empty.
I tested this on Moodle 4.1.
What is exactly your Moodle version ? Have you got the same behaviour ?
Olivier

**Comment by cputzenlechner** [comment]
Hi Olivier,
currently we are using 3.11. But we Upgrade to 4.1 on 6th of November. I've tested with 3.11 as well as with Version 4.1. I can just confirm the behaviour you have described - the activity is empty. I've tested it with another block funktion "sharing cart" (we try to recommend this kind of copying activities or materials instead of the import function to our lecturers). Unfortunately there is the same behaviour - no column headers are copied.
Kind regards
Christian

**Comment by oliviervalentin** [comment]
Hi Christian,
thanks for your precision. Very strange that Moodle can backup and restore an activity with all contents, but can't/doesn't do it when simply copying it ! Further research will be needed...
Olivier

**Comment by oliviervalentin** [comment]
Hi Christian,
the copy of columns titles when duplicating activity will be integrated soon.

After discussing through forums, duplication initially doesn't take any personal datas. It seems to just copy the activity with its parameters, but it doesn't necessary take any other datas. 
So in Sticky Notes case, it is logical in Moodle classical working not to take columns titles. But I understand very well that, for a duplication, it's a shame this information was not duplicated, and teacher had to start again from scratch.

I close this ticket, next update will integrate the columns copy when duplicating activity.
Thanks again for your message !
Olivier
