### ISSUE TITLE
Adding links and images

### ISSUE THREAD

**Issue by IlanAdivi1** [oliviervalentin/moodle-mod_stickynotes#27]
Hello Olivier,

There is a demand from users that the option of attaching links and images be added to the Sticky-notes.

So it would be great if you could add it :)

**Comment by oliviervalentin** [comment]
Hi Ilan,
thank you for you message !

I already thought about this, but I'm not sure to do it.
Indeed, my objective with this activity was to offer the same goal as a Sticky notes wall in real life. I just imagined something where you can note small things and where you are , contrary to a Paddlet where you can indeed put images, links, videos... but a Paddlet is online ! 

I understand this demand, but not sure to integrate it to Sticky Notes one day... but if this makes sense to you, and you imperatively need this function, I suggest you to test the Board activity, which is precisely a Paddlet activity, including all medias and most functions I offer in Sticky Notes.
I remember this activity was published at the same as Sticky Notes, and is produced by Brickfield, which is partner with Moodle. Maybe this could help !

Best regards,
Olivier
