### ISSUE TITLE
Component name and instructions

### ISSUE THREAD

**Issue by IlanAdivi1** [oliviervalentin/moodle-mod_stickynotes#28]
Hello Olivier,

There are a few things that our team has seen that need fixing in the Sticky-notes you've developed:
I saw that there are duplicates in the component name and instructions.

**The system management setting "Display description in activity" is unnecessary, and the button "Display instructions" is unnecessary**

https://artzi.lms.education.gov.il/mod/stickynotes/view.php?id=1769290&lang=en

It seems that the name of the component appears twice - 
you should keep the name of the component that appears at the top,
and remove the name of the component that appears at the bottom part.

![section name](https://github.com/oliviervalentin/moodle-mod_stickynotes/assets/156344815/6c5aea5d-2c8c-42ca-ad09-d89e3b24b3f2)

It seems that the "Display instructions" button is unnecessary,
because the instructions are already displayed once (on the gray background),
So there is no need to display the instructions a second time with the button.

Therefore, because the "Display instructions" button is unnecessary, 
there is no need to set the system management "Display description in activity".

![notes settings](https://github.com/oliviervalentin/moodle-mod_stickynotes/assets/156344815/9cf49c01-cac9-4704-9c32-460a0b66a68e)

![duplicate instructions](https://github.com/oliviervalentin/moodle-mod_stickynotes/assets/156344815/6ba929fd-d151-4181-8528-6d2b680cbcd8)

Thanks,
Ilan

**Comment by oliviervalentin** [comment]
Hello Ilan,
I think I had possibility to show description when I started to code this plugin for Moodle 3. This feature doesn't seem to be useful anymore.
Double title is not necessary too...
I will drop those two elements as soon as possible.
Thank you for your comments !
Olivier

**Comment by oliviervalentin** [comment]
Next version I will soon release will solve those problems.
I close this ticket !
Best regards,
Olivier
