### ISSUE TITLE
After submitting form_note, $col is not set in note.php

### ISSUE THREAD

**Issue by djarran** [oliviervalentin/moodle-mod_stickynotes#32]
After creating a note for a given column and submitting the form, the following error is shown:

```
 Warning: Trying to access array offset on value of type null in /var/www/site/mod/rstickynotes/note.php on line 101
``` 

This is the code on line 101 in `note.php`:
```php
// Define the page title for creating form.
$settitle = get_column_title($col);
$pagetitle = (get_string('createnote_title', 'stickynotes')).'"'.$settitle['title'].'"';

...

function get_column_title($col) {
    global $DB;
    $record = $DB->get_record('stickynotes_column', array('id' => $col));
    if (!$record) {
        return;
    } else {
        $column['title'] = $record->title;
    }
    return $column;
}

```

After submitting the form, the `$col` parameter is empty as it is not passed to the form definition. Consequently, the `get_column_title` returns a null value, and is attempted to be accessed still.

**Comment by oliviervalentin** [comment]
Dear Djarran,
ok fixed. For this case, I will put a test to check if variable is defined. If yes, that means form is shown. If not, it means form has been posted.
I will soon push a new version for the plugin.
Thank you once again for reporting all theses bugs ! :)
Olivier
