### ISSUE TITLE
Hardcoded in english?

### ISSUE THREAD

**Issue by dinism** [oliviervalentin/moodle-mod_stickynotes#8]
Thanks for the plugin.
I'm a PT-PT translator.

I can't find this string in AMOS.
![imagem](https://user-images.githubusercontent.com/14828021/131191894-497de83d-41d4-4a66-8add-3d55c6b19a46.png)

**Comment by oliviervalentin** [comment]
Thanks for your comment !
Indeed, my fault, I have forgotten this text, there is no AMOS string related. It takes place in lib.php, in two lines (292 and 320).
I will change this as soon as possible.
Olivier

**Comment by oliviervalentin** [comment]
OK debbuged ! :)
