### ISSUE TITLE
Description / Reorder Columns

### ISSUE THREAD

**Issue by xdaniel2063** [oliviervalentin/moodle-mod_stickynotes#9]
Thanks for this plugin. I think it could be really useful.

Two things, maybe bugs or feature requests ;-):
a) Is it possible to show the description on the activitites page?
b) Could you implement a way to reorder the columns?

**Comment by oliviervalentin** [comment]
Hi, thanks for your message !
a) when you say to "show description on activities page", do you mean to show description inside the Sticky Notes activity ? For example above columns ?
b) I will think about possibility to reorder columns. I dont't know if it will be with drag-and-drop, or just in edit form.
Olivier

**Comment by xdaniel2063** [comment]
Hi Oliver,
thanks for the reply. 
a) Yes I mean inside the activity. This could be great for giving instructions or explanations. Please find a screenshot here: https://i.imgur.com/bSNZqe0.png
b) Drag and Drop would be great, but in the form is ok too. 
Best, Daniel

**Comment by oliviervalentin** [comment]
Hi,
good idea for description ! Saying that, it would be useful too to see color meanings if set... I will think about it, for example with a collapsed menu so it doesn't take too much place.
For drag and drop, I will see that with the person who helped me to code that.
Olivier

**Comment by oliviervalentin** [comment]
I close this issue for now...
The "show description" enhancement had been added in new version.
Concerning reordering columns, I'm thinking about other enhancement around columns admin, so it won't be added for now... but it stays in my mind ! :)
Olivier
